FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgomp1 \
        build-essential \
        gcc \
        g++ \
        libglib2.0-0 \
        libsm6 \
        libxext6 \
        libxrender1 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    paddlepaddle==2.6.2 \
    paddleocr==2.10.0

CMD ["python", "-c", "import paddleocr; print('OK')"]